In [1]:
import pandas as pd

In [6]:
df_products = pd.read_csv('../data/raw/products.csv')
print(df_products.columns)

Index(['product_id', 'product_name', 'aisle_id', 'department_id', 'prices'], dtype='str')

In [7]:
df_deparments = pd.read_csv("../data/processed/departments_t.csv")
print(df_deparments.columns)

Index(['department_id', 'department'], dtype='str')

In [20]:
df_products_departments = pd.merge(
    df_products,
    df_deparments,
    on= 'department_id',
    how= 'left'
    )
df_products_departments.head(7)

,product_id,product_name,aisle_id,department_id,prices,department
0,1,Chocolate Sandwich Cookies,61,19,5.8,snacks
1,2,All-Seasons Salt,104,13,9.3,pantry
2,3,Robust Golden Unsweetened Oolong Tea,94,7,4.5,beverages
3,4,Smart Ones Classic Favorites Mini Rigatoni Wit...,38,1,10.5,frozen
4,5,Green Chile Anytime Sauce,5,13,4.3,pantry
5,6,Dry Nose Oil,11,11,2.6,personal care
6,7,Pure Coconut Water With Orange,98,7,4.4,beverages

In [22]:
df_aisles = pd.read_csv('../data/raw/aisles.csv')

In [28]:
df_products_enriched= pd.merge(
    df_products_departments,
    df_aisles,
    on= 'aisle_id',
    how= 'left'
    )
df_products_enriched.head()

,product_id,product_name,aisle_id,department_id,prices,department,aisle
0,1,Chocolate Sandwich Cookies,61,19,5.8,snacks,cookies cakes
1,2,All-Seasons Salt,104,13,9.3,pantry,spices seasonings
2,3,Robust Golden Unsweetened Oolong Tea,94,7,4.5,beverages,tea
3,4,Smart Ones Classic Favorites Mini Rigatoni Wit...,38,1,10.5,frozen,frozen meals
4,5,Green Chile Anytime Sauce,5,13,4.3,pantry,marinades meat preparation

In [30]:
df_orders_train= pd.read_csv('../data/raw/order_products_train.csv')

In [37]:
df_order_products_train= pd.read_csv('../data/raw/order_products_train.csv')

In [40]:
df_train_transactions= pd.merge(
    df_orders_train,
    df_order_products_train,
    on= 'order_id',
    how= 'inner'
)
df_train_transactions.head()

,order_id,product_id_x,add_to_cart_order_x,reordered_x,product_id_y,add_to_cart_order_y,reordered_y
0,1,49302,1,1,49302,1,1
1,1,49302,1,1,11109,2,1
2,1,49302,1,1,10246,3,0
3,1,49302,1,1,49683,4,0
4,1,49302,1,1,43633,5,1

In [51]:
df_train_transactions.rename(columns={'product_id_y':'product_id'}, inplace=True)

In [50]:
df_train_transactions.drop(columns=['product_id_x', 'add_to_cart_order_x', 'reordered_x'], inplace=True)

In [52]:
df_train_analytic= pd.merge(
    df_train_transactions,
    df_products_enriched,
    on='product_id',
    how="left"
)
df_train_analytic.head()

,order_id,product_id,add_to_cart_order_y,reordered_y,product_name,aisle_id,department_id,prices,department,aisle
0,1,49302,1,1,Bulgarian Yogurt,120.0,16.0,9.1,dairy eggs,yogurt
1,1,11109,2,1,Organic 4% Milk Fat Whole Milk Cottage Cheese,108.0,16.0,2.0,dairy eggs,other creams cheeses
2,1,10246,3,0,Organic Celery Hearts,83.0,4.0,4.5,produce,fresh vegetables
3,1,49683,4,0,Cucumber Kirby,83.0,4.0,13.2,produce,fresh vegetables
4,1,43633,5,1,Lightly Smoked Sardines in Olive Oil,95.0,15.0,1.7,canned goods,canned meat seafood