## Dates

In [1]:
from datetime import datetime, date, timedelta

In [42]:
my_date = date(year=2025,month=3,day=24)

In [43]:
type(my_date)

datetime.date

In [51]:
my_time = datetime(year=2025,month=3,day=24, hour=14,minute=59,second=58)

In [52]:
my_time

datetime.datetime(2025, 3, 24, 14, 59, 58)

In [53]:
today = date.today()
today

datetime.date(2026, 3, 24)

In [54]:
now = datetime.now()
now

datetime.datetime(2026, 3, 24, 22, 12, 34, 209600)

In [55]:
my_date.strftime("%Y/%m/%d")

'2025/03/24'

In [56]:
my_date.strftime("%Y-%m-%d")

'2025-03-24'

In [50]:
my_date.strftime("%b %d %y")

'Mar 24 25'

In [57]:
my_date

datetime.date(2025, 3, 24)

In [60]:
start_date = my_date
end_date = datetime(2026,4,4)

In [64]:
delta = end_date -  start_date
delta

TypeError: unsupported operand type(s) for -: 'datetime.datetime' and 'datetime.date'

In [63]:
rd = (today + timedelta(days=5)).strftime("%b %d %y")
rd

'Mar 29 26'

### Dates with Pandas

In [23]:
import pandas as pd

df_dates = pd.DataFrame({
    "customer_id": [101, 102, 103, 104, 105],
    "signup_date": ["2024-01-15", "2024-02-20", "2024-03-05", "2024-03-18", "2024-04-10"],
    "last_purchase": ["2024-06-01", "2024-06-15", "2024-07-01", "2024-07-08", "2024-07-12"]
})

df_dates

   customer_id signup_date last_purchase
0          101  2024-01-15    2024-06-01
1          102  2024-02-20    2024-06-15
2          103  2024-03-05    2024-07-01
3          104  2024-03-18    2024-07-08
4          105  2024-04-10    2024-07-12

In [24]:
df_dates.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   customer_id    5 non-null      int64
 1   signup_date    5 non-null      str
 2   last_purchase  5 non-null      str
dtypes: int64(1), str(2)
memory usage: 352.0 bytes

In [28]:
df_dates['signup_date'] = pd.to_datetime(df_dates['signup_date'])
df_dates['last_purchase'] = pd.to_datetime(df_dates['last_purchase'])

In [29]:
df_dates.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   customer_id    5 non-null      int64
 1   signup_date    5 non-null      datetime64[us]
 2   last_purchase  5 non-null      datetime64[us]
dtypes: datetime64[us](2), int64(1)
memory usage: 252.0 bytes

In [30]:
df_dates.to_csv('../data/test.csv', index=False)

In [ ]:
test = pd.read_csv('../data/test.csv',parse_dates=['signup_date'
                                                   ])

In [31]:
df_dates.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   customer_id    5 non-null      int64
 1   signup_date    5 non-null      datetime64[us]
 2   last_purchase  5 non-null      datetime64[us]
dtypes: datetime64[us](2), int64(1)
memory usage: 252.0 bytes

In [36]:
df_dates["signup_year"] = df_dates["signup_date"].dt.is_year
df_dates["signup_year"] = df_dates["signup_date"].dt.is_month
df_dates["signup_year"] = df_dates["signup_date"].dt.is_day

AttributeError: 'DatetimeProperties' object has no attribute 'is_year'

In [38]:
df_dates["signup_month_name"] = df_dates["signup_date"].dt.month_name()

In [39]:
df_dates

   customer_id signup_date last_purchase  signup_year signup_month_name
0          101  2024-01-15    2024-06-01        False           January
1          102  2024-02-20    2024-06-15        False          February
2          103  2024-03-05    2024-07-01        False             March
3          104  2024-03-18    2024-07-08        False             March
4          105  2024-04-10    2024-07-12        False             April

In [41]:
import pandas as pd
import numpy as np
import plotly.express as px

np.random.seed(42)
px.defaults.template = "plotly_white"

months = pd.date_range("2024-01-01", periods=6, freq="MS")
regions = ["North", "South", "East"]
products = ["A", "B"]

rows = []

for month in months:
    for region in regions:
        for product in products:
            sales = np.random.randint(80, 220)
            customers = np.random.randint(20, 90)
            units = np.random.randint(10, 70)
            
            rows.append([month, region, product, sales, customers, units])

df_plotly = pd.DataFrame(
    rows,
    columns=["month", "region", "product", "sales", "customers", "units"]
)

df_plotly["month_name"] = df_plotly["month"].dt.strftime("%b")
df_plotly.head()

ModuleNotFoundError: No module named 'plotly'